openshiftio/openshift.io

app/component-analyses.ts, app/index.html, app/index.ts
- Added inline form to pick values of "ecosystem", "component", "version"
- fetch component analyses result based on user input
- show response in view
=> Component analyses initial commit

README.md, app/component-analyses.ts, app/stack-analyses.ts
changes in api locator and README as per prod-preview api endpoints of bayesian
=> changes as per prod-preview api endpoints of bayesian

app/component-analyses.ts, app/index.html
- added closing tag for form, removed toolbar, header title change
- cleared table item before data binding
=> Component analyses form ux

app/index.html, assets/stylesheets/custom.scss, assets/stylesheets/variables.scss
update the register button so that it is not cut off; update base font size for placeholder text
=> fix(ui): fix button sizing and font defaults

assets/stylesheets/_layout.scss
remove height styling that breaks in Safari, causing form to not render. cleanup commented code.
=> fix(ui): remove height styling from hero element

app/header.scss, app/index.html, assets/stylesheets/custom.scss
add the navigation items from the wireframe (keeping to PF nav design) and adjust resizing of elements to fix overflow
=> fix(navigation): add wireframe navigation and adjust resizing

app/index.html
add a placeholder status indicator to the header as a roll-up identifier
=> fix(status): add placeholder indicator to header

app/index.ts
update the redirect from /'username' to /_home
=> fix(login): update redirect to _home

app/component-analyses.ts, app/recommender.scss
changes due to change in API schema of component-analysis
=> changes due to change in API schema of component-analysis

app/component-analyses.ts, app/index.html, app/recommender.scss, app/stack-analyses.ts
created grid and binded values for CVEs
=> created grid and binded values for CVEs

app/index.html, assets/stylesheets/_layout.scss
remove the registration inputs from the hero element. link to RHD registration not included.
=> fix(reg): remove registration inputs

app/index.html, assets/stylesheets/_layout.scss
adds help/info text for component analyses
1) adds proper placeholder/title for Ecosystem,Component,Version
2) adds info icon along with description
Below are the changes
=> adds help/info text for component analyses

app/index.html, app/stack-analyses.ts, assets/stylesheets/_layout.scss
1)adds help/info text about manifest
2)restricts file upload only for .xml, .json for now
as below
=> adds help/info text about manifest, restricts file upload

app/index.html, assets/stylesheets/custom.scss
add the 'All policies...' to footer and fix alignment of social icons
=> fix(footer): fix footer content and positions

app/index.html
update header text to new copy
fixes https://github.com/openshiftio/www.openshift.io/issues/55
=> fix(header): update headline text

app/header.scss, app/index.html, app/index.ts
remove the Explore link from the navigation; adjust alignments
fixes https://github.com/openshiftio/www.openshift.io/issues/57
=> fix(nav): remove links from navigation

app/index.html
remove the Features title from the second section
fixes https://github.com/openshiftio/www.openshift.io/issues/59
=> fix(section): remove Features title from section

app/index.html
adds select box for ecosystem values(Maven, Npm , Python)
=> adds selectbox for ecosystem values

app/index.html
update the Community copy with the new text
fixes https://github.com/openshiftio/www.openshift.io/issues/71
=> fix(copy): update Community copy

Dockerfile.deploy, src/app/index.ts, src/config/www.openshift.io.config.json, webpack.config.js
This reverts commit 67f440d3de86887c2ebe866cf8722b30d2e18b6e.
=> Revert "Revert "feat: set waitlist_url at runtime""

src/app/index.html
update layout to improve column organization for large screens
=> fix(layout): add columns for large screens

openshift/www.openshift.io.app.yaml
Please, let me know if you don't think these limits are reasonable.
=> Add resource requests/limits

src/app/index.html
fix duplicate copy in the cards
fixes https://github.com/openshiftio/www.openshift.io/issues/95
=> fix(copy): fix duplicate copy

src/app/index.html, src/assets/stylesheets/_footer.scss
update links in footer and update styles to accommodate new links
fixes https://github.com/openshiftio/www.openshift.io/issues/98
=> fix(footer): update links in footer

src/app/index.html
change Home link to Account Home to match product navigation
fixes https://github.com/openshiftio/www.openshift.io/issues/97
=> fix(nav): change Home to Account Home

README.md
outstanding questions is stackoverflow tag correct ? waiting on Heinz.
Should we add more specific repositories ?
=> first version with community details

src/app/index.html
update the tagline, per request
fixes https://github.com/openshiftio/openshift.io/issues/102
=> fix(tagline): update the tagline

src/app/index.html
change the text of the primary CTA from Register to Sign Up
=> fix(button): change text from Register to Sign Up

openshift/www.openshift.io.app.yaml
@vpavlin doing the manual route to just get the replica count up for now.
=> scale up to running 3 replicas

src/app/index.html, src/assets/stylesheets/features.scss
fix items that were found to be broken upon further inspection
=> fix(punchlist): fix items for web standards

src/assets/stylesheets/_footer.scss
fix footer content wrapping on small-medium screens
=> fix(footer): fix footer content wrapping

src/app/index.html, src/app/pages/_learn-more/planning-tools.html
add copy for card3 (planning tools)
=> fix(card3): ad copy for card3

src/app/index.html, src/assets/stylesheets/features.scss
update the hover visuals for the cards to show the entire card as clickable and change heading and learn more to blue
=> fix(cards): update hover visuals for cards

src/app/index.html, src/assets/stylesheets/_layout.scss, src/assets/stylesheets/features.scss
update banner layout and sizing
=> fix(banner): update banner layout

src/app/index.html
update to latest version of copy
=> fix(copy): update copy with latest

src/assets/stylesheets/features.scss
fix screenshot alignment and sizing on mobile devices
=> fix(screenshots): fix screenshot alignment

src/app/index.html, src/assets/stylesheets/_layout.scss, src/assets/stylesheets/custom.scss
update layout, change content copy and add intro video
=> fix(content): further updates to content and layout

src/assets/stylesheets/custom.scss
remove line height and add padding
=> fix(list): fix list line height

src/assets/sass/_buttons.scss, src/assets/sass/_footer.scss
fix missed updates for refreshed code guidelines
=> fix(guidelines): second update of code guidelines

src/app/components/header.html, src/app/components/header.scss, src/app/index.html
switch logo type and add subtext
=> fix(header): update header logo and subtext

src/app/index.html
update cache controls in header to set expiration time, storage and validation
=> fix(cache): update cache controls in header

src/app/index.html
update cache settings to prevent caching problems when site styles/images are updated
=> fix(cache): update cache settings

src/app/index.html
fix abrupt paragraph ending and add ending text.
=> fix(text): fix paragraph ending

src/app/index.html
update the text in the first paragraph from "performance code pilot" to "performance co-pilot"
=> fix(text): update text in 1st paragraph

src/app/index.html
update the content and grammer of various paragraphs
=> fix(text): update content and grammar

src/app/index.html, src/app/pages/_learn-more/better-decisions.html, src/app/pages/_learn-more/end-to-end.html, src/app/pages/_learn-more/install-nothing.html, src/app/pages/_learn-more/microservices.html, src/app/pages/_learn-more/planning-tools.html, src/app/pages/_learn-more/rhdp-membership.html
Why:
* Because it is Log Out everywhere else
This change addreses the need by:
* search and replace for Sign Out to Log Out
=> fix(text): Sign Out -> Log Out

nginx.conf
As done for other nginx configurations, we want json as the output format for the logs
=> Set json format for the nginx logs

src/app/index.ts
Related to https://github.com/fabric8-services/fabric8-auth/issues/64
=> Logout users before login

src/assets/stylesheets/_layout.less
fixes https://github.com/openshiftio/openshift.io/issues/822
=> fix(footer): fix text cutoff in footer

src/app/index.html, src/app/index.ts, src/app/pages/features.html, src/app/pages/get-involved.html, src/assets/stylesheets/_navigation.less
Update the redirect logic from the marketing page to allow for navigation of Features and Get Involved
related to https://github.com/fabric8-ui/fabric8-ux/issues/745
=> fix(redirect): Update redirect logic

README.md
=> Mention in README what this repository contains

src/app/index.html, src/app/pages/documentation.html, src/app/pages/features.html, src/app/pages/get-involved.html
Update footer from 2017 to 2018.
=> fix(footer): Update date in footer

src/app/index.html, src/app/pages/documentation.html, src/app/pages/features.html, src/app/pages/get-involved.html
The copyright date will now automatically update when the year changes.
=> fix(date): set copyright date to dynamic element

src/app/index.html
fix the merge issue that created multiple (and conflicting) sign up buttons.
=> fix(button): fix merge issue

src/app/index.ts
Do not display login and logout buttons simultaneously during
redirection delay period while user is waiting to be redirected to the
main OSIO application _gettingstarted state.
fixes https://github.com/openshiftio/openshift.io/issues/2456
=> fix(home-page): do not display login and logout simultaneously

src/app/index.html
Update the main content to to use CodeReady Toolchain - [OSIO-1113](https://openshift.io/openshiftio/Openshift_io/plan/detail/1113)
Reference: https://github.com/openshiftio/openshift.io/issues/4364
=> Update the main content to to use CodeReady Toolchain (OSIO-1113).

src/app/index.html
Update page title to Code Ready Toolchain [OSIO-1114](https://openshift.io/openshiftio/Openshift_io/plan/detail/1114)
Reference: https://github.com/openshiftio/openshift.io/issues/4364
=> Update page title to Code Ready Toolchain (OSIO-1114)

src/app/pages/features.html
Update all OSIO references to CodeReady Toolchain on the Features page - [OSIO-1115](https://openshift.io/openshiftio/Openshift_io/plan/detail/1115)
Reference https://github.com/openshiftio/openshift.io/issues/4364
=> Update all OSIO references to CodeReady Toolchain on the Features page

src/app/pages/get-involved.html
Update all OSIO references to CodeReady Toolchain on the Get Involved page - [OSIO-1116](https://openshift.io/openshiftio/Openshift_io/plan/detail/1116)
Reference: https://github.com/openshiftio/openshift.io/issues/4364
=> Update all OSIO references to CodeReady Toolchain on the Get Involved page

nginx.conf, src/app/index.html, src/assets/stylesheets/_flex.less, src/assets/stylesheets/_grid.less, src/assets/stylesheets/_layout.less
@joshuawilson @christianvogt @nimishamukherjee Please review
=> feat(osredirect):Redirect OSIO URLs to Landing page and update Header/Footer

src/app/index.html, src/app/index.ts
Redirect to che.openshift.io if the user is already logged in.
=> OSIO redirection to che.openshift.io

nginx.conf
@christianvogt @joshuawilson @nimishamukherjee Please review. URL will update with restriction posed to pages
=> fix(osredirect): Update URL and restrict access to pages/

src/app/index.html, src/assets/stylesheets/_layout.less
Updated copy of index page to align with request.
zoomed out screenshot of index page content:
=> fix(copy): update the copy of the index page
