openshiftio/openshift.io

nginx.conf

any content not on the local service instance, should be passed along to the f8ui/ service. 
This is going to be a perf hit when we start scaling, and I've made a note to revisit once we can measure things to see if we can do this better, down the road.

proxy pass to the console on 404

---

cico_build_deploy.sh

we've had issues on and off with xip so consolidating all the content down the devshift.net registry.

use a proper dns name for the registry, since xip.io is unreliable

---

nginx.conf

the internal service runs on port 8080, we need to use that to use the service backend instead of the :80 default.

need to use port 8080

---

app/index.html
app/stack-analyses.ts

adds template in case of no recommendations for stack analysis with default message and styling of response
Stack response view with above changes

adds template in case of no recommendations for stack analysis

---

app/component-analyses.ts
app/index.html
assets/stylesheets/recommender.scss

Component analyses response view:
1) removes grid view used to represent response of Component analyses 
2) adds card based view with multiple groups i.e Code metric, Summary, Version, CVE
Below is first version

replaced grid with cards for component analyses response

---

src/app/index.ts

Removed ?link=true param from login.
User will now be redirected to the getting started page.
Getting started will handle linking GitHub and OpenShift accounts.

fix(login): Redirect to getting started page

---

src/app/index.ts

setTimeout() uses a 32 bit int to store the delay. So the max value allowed is 2147483647
But since we switched to 30 day tokens the token expiry now is bigger than that int which causes immediate refreshing.
Actually we need to refresh in 10 minutes or in 90% of the expiry time whatever is sooner so that will fix the problem.
Fixes https://github.com/fabric8io/fabric8-ui/issues/1049

Avoid refreshing token constantly if the timeout is too big

---

nginx.conf

We should change the error_log level to warn. The info level is fairly verbose and shows information we don't particularly care about such as when keepalive connections are closed, timeouts...
`2017/06/12 20:55:46 [info] 24#0: *402112 client 10.130.0.1 closed keepalive connection (104: Connection reset by peer)`
The warn level is where is start being useful (warning, errors, etc...)

Change nginx error_log level to warn

---

openshift/www.openshift.io.app.yaml

www-openshift-io is a downstream route that does a redirect.

default route should be named openshift-io

---

nginx.conf

For some reason having index inside location
makes nginx treat the whole location as a local static
filesystem and ignore the proxy pass options
resulting in 405 Method not allowed on DELETE
instead of forwarding the request to the proxy pass.
Related to openshiftio/openshift.io#542

Move index directive outside of location

---

Dockerfile.deploy

We need to use the same image of fabric8-ui.

Update docker image to point to the latest one

---

.stylelintignore
src/app/index.html
src/app/pages/features.html
src/app/pages/get-involved.html
src/assets/stylesheets/_layout.less
src/assets/stylesheets/_typography.less

update the CDN link for the Overpass fonts to point to Google Fonts, which uses https
fixes https://github.com/openshiftio/openshift.io/issues/821

fix(overpass): change CDN link for Overpass fonts

---

nginx.conf

This change allows nginx to retrieve the real client IP from the X-Forwarded-For header set by the Openshift routers

set real IP from X-Forwarded-For header

---

src/app/index.html
src/assets/stylesheets/_layout.less

Add a chat button to the homepage for easy access to the chat.openshift.io environment.
closes https://github.com/openshiftio/openshift.io/issues/1185

feat(chat): add Chat button to homepage

---

webpack.config.js

This change permits the serving of any PDF files found in /src/assets/documents via a URL directly from the root of the application.
e.g. /src/assets/documents/foo.pdf is available via https://openshift.io/foo.pdf
I also moved osiogettingstarted.pdf to the new documents directory, to resolve issue #1392

fox(doc): Serve getting started PDF document from root

---

.stylelintrc
src/app/pages/get-involved.html
src/assets/stylesheets/_flex.less
src/assets/stylesheets/_footer.less
src/assets/stylesheets/_layout.less
src/assets/stylesheets/osio.less

Update layout to support older browsers that cannot render CSS Grid. Utilize flexbox as a fallback display property.
fixes https://github.com/fabric8-ui/fabric8-ux/issues/840
related to https://github.com/openshiftio/openshift.io/issues/2050

fix(layout): Update browser support

---

src/app/index.html
src/app/index.ts
src/app/pages/documentation.html
src/app/pages/get-involved.html
src/app/pages/not-authorized.html
src/assets/stylesheets/_grid.less
src/assets/stylesheets/_navigation.less
webpack.config.js

Add a Documentation page with link to OpenShift.io Getting Started and User Guides.

feat(docs): Add Documentation page with links

---

src/app/index.html

3 changes to align with the state of the site:  
Changed title from "Introducing" to "Welcome to OpenShift.io". 
Changed CTA button from "Sign up for the Preview" to "sign up today". 
Removed the line "Currently waitlisting registrants."

home page update March 23

---

.github/uxd_template.md

Create a UX Issue Template for UXD to utilize when creating new Issues.
The URL for creating the template will be https://github.com/openshiftio/openshift.io/issues/new?template=uxd_template.md
This also creates a default (and blank) issue template from with any interaction with 'New Issue' will use by default.
Related to https://github.com/openshiftio/openshift.io/issues/2880

fix(template): Create a UX Issue Template

---

Dockerfile.deploy.rhel
cico_build_deploy.sh
openshift/www.openshift.io.app.yaml

Enable build on RHEL if TARGET=rhel.
As part of an effort to migrate the services running in OSIO from CentOS
to RHEL, we are ready to push out the RHEL based image for this service
into staging.
This PR includes a new RHEL based dockerfile for the deployment of the service.
This dockerfile will be built when this variable is set: TARGET=rhel. The build
scripts have been adapted to take this into consideration, and to push the image
to different namespaces if the TARGET is rhel or not.
Currently the deployment builds happen on empty baremetal machines. The build
script will be executed a second time to build and push the deployment file if
TARGET=rhel, so some changes in the build script are to ensure that it will work
if executed a second time.
The OpenShift template has also been …

Deploy on RHEL based container

---

nginx.conf

These references are leftovers and are not used anymore.

Remove reference to more_headers module

---

Dockerfile.deploy.rhel
cico_build_deploy.sh
openshift/www.openshift.io.app.yaml

This PR is part of the effort to move to Quay.
This is the list of changes in this PR:
- Pushes to Quay instead of the Devshift registry
- Uses an image hosted in Quay to build the RHEL based container image
- Uses the new env-toolkit to load variables from jenkins-env
- Changes the default path of the image to quay (note that this should not affect production because it is overridden in the saas repo)
A companion PR should have been submitted to the appropriate saas repo to change the staging url from devshift to quay. The PR to the saas repo should be merged before this one.
https://github.com/openshiftio/saas-openshiftio/pull/922

Move to Quay.io

---

cico_build_deploy.sh

It looks like BUILD_TIMESTAMP is not used, removing it to avoid
confusions down the road.

Removes BUILD_TIMESTAMP which is not used

---

src/app/index.html
src/app/index.ts
src/assets/stylesheets/_layout.less

- **index.html:** updated the redirect to che url to be dynamic based off of the current `location.hostname` such that in prod-preview we redirect to `https://che.prod-preview.openshift.io`
@abhinandan13jan mentioned that the new sign-up link wasn't working correctly. Also fixed this link to navigate the user to the sign-up page.
Added a few minor layout tweaks:
- bold list item titles
- add padding to content area for mobile
- reduce text size of secondary content
- fix a couple of links which didn't include the full text in the link

 fix(redirect): fix che redirect url to support prod-preview

---

src/app/index.ts

Updated url creation for che redirect to use `location.hostname` in order to support redirect to `che.prod-preview.openshift.io`.

fix(redirect): fix another instance of che redirect to support prod-preview

---

nginx.conf
webpack.config.js

Turns out the last update that was made worked locally but failed in prod-preview :/
- Removed the extra marketing pages from the webpack build so that they never show up in the deployed directory. Only the index.html page is present. This makes editing rules for nginx.conf easier.
- Re-instated the gzip rules that were removed.
- Updated the location rules to add a 301 rewrite so that any attempt to access a url that isn't present gets immediately routed to the root page and the URL gets updated accordingly.
eg. openshift.io/features.html => openshift.io

fix(redirect): remove extra marketing pages and fix rewrite rules

---

nginx.conf

Locally I was testing `localhost:8080`. It so happens that the container port is also `8080` so when a redirect happened, the correct port was being used in a local test environment. However in `prod-preview` there is no port. When nginx performed the redirect, it sent the user to `https://prod-preview.openshift.io:8080` which is incorrect.
Tested locally with container port being `8080` and published port being `9090`. Successfully redirected to `localhost:9090` where before it would fail.
Turns out that we need to ensure that the request port needs to somehow be specified so that the container port isn't used in the redirect url.
Thanks to @alexeykazakov for spotting the wrong port in the headers. He also mentioned that we should use status code `307` for the redirect instead of `301` …

fix(redirect): fix container port being used in redirect instead of request port

---

src/app/index.html

URLs in links to Che and CRW were swapped on the index page. This fixes it.

Switch URLs to fix links to products
